config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  root to: "index#index"
  devise_for :users

  resources :index, only: [:index]
  resources :fundations
  resources :services
  resources :calendar, only: [:index]
  resources :chat_rooms, only: [:new, :create, :show, :index]

  mount ActionCable.server => '/cable'
  mount SimpleDiscussion::Engine => "/forum"
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'login', to: 'login#login' #to: define el controlador y el metodo al que apunta

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/fundation.rb
class Fundation < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S - %Y %m %d')
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include SimpleDiscussion::ForumUser

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_params, if: :devise_controller?

	def configure_devise_params
	   devise_parameter_sanitizer.permit(:sign_up) do |user|
	     user.permit(:name, :lastname, :document, :phone, :profession, :fundation_id, :role_id, :state_id, :email, :password, :password_confirmation)
	   end
	end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to "/events", notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to "/events", notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to "/events", notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_time, :end_time)
    end
end

app/controllers/fundations_controller.rb
class FundationsController < ApplicationController

  def index
    @fundation = Fundation.all
  end

  def new
    @fundation = Fundation.new
  end

  def create
    @fundation = Fundation.new(allowed_params)

    respond_to do |format|
      if @fundation.save
        format.html { redirect_to "/fundations/new" }
      else
        format.html { render :new }
      end
    end
  end

  private

  def allowed_params
    params.require(:fundation).permit(:fundation_name, :address, :phone, :mail)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @service = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(allowed_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to "/services/new" }
      else
        format.html { render :new }
      end
    end
  end

  private

  def allowed_params
    params.require(:service).permit(:service_name, :description, :cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "user-chat.png", size: "40x40", alt: "Edit Entry"
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fundations_helper.rb
module FundationsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/simple_discussion/forum_posts_helper.rb
module SimpleDiscussion::ForumPostsHelper
  # Override this to use avatars from other places than Gravatar
  def avatar_tag(email)
    gravatar_image_tag(email, gravatar: { size: 40 }, class: "rounded avatar")
  end

  def category_link(category)
    link_to category.name, simple_discussion.forum_category_forum_threads_path(category),
      style: "color: #{category.color}"
  end

  # Override this method to provide your own content formatting like Markdown
  def formatted_content(text)
    simple_format(text)
  end

  def forum_post_classes(forum_post)
    klasses = ["forum-post", "card", "mb-3"]
    klasses << "solved" if forum_post.solved?
    klasses << "original-poster" if forum_post.user == @forum_thread.user
    klasses
  end

  def forum_user_badge(user)
    if user.respond_to?(:moderator) && user.moderator?
      content_tag :span, "Mod", class: "badge badge-default"
    end
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li style="list-style:none;"><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room), class: "list-group-item" %></li>

app/views/chat_rooms/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <p class="text-justify">
                 Aqui podras encontrar varias salas de chat con temas que esperamos te interecen. 
                 El objetivo principal de este sitio es permitir aclarar tus dudas sobre la problematica 
                 de la drogadiccion para que tomes la mejor decision. </p>

            <p class="text-justify">  En nuestra sala uno de nuestros profesionales te estara esperando. </p> 

            <p class="font-weight-bold"> ¡Escoge tú sala y empieza a chatear!.</p>
        </div>

        <div id="chat_salas" class="col-md-8" style="padding: 0px 20px 0px 30px; height: 300px;">
    		<h4>Salas</h4>

            <ul class="list-group">
               <%= render @chat_rooms %>
            </ul>
 		</div>
    </div>
</div>

app/views/chat_rooms/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
             <div class="row">
                <div class="col-md-6 mx-auto">

					<h1>Nueva Sala</h1>

					<%= form_for @chat_room do |f| %>
					  <div class="form-group">
					    <%= f.label :'Nombre de la nueva sala' %>
					    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
					  </div>
                     <div class="actions">
					    <%= f.submit "Agregar!", class: "btn btn-success float-right" %>
                      </div>
					<% end %>

 				</div>
            </div>
        </div>
    </div>
</div>

app/views/chat_rooms/show.html.erb
<div class="container">
    <div class="row" style="margin-top: 60px;">
		<div class="container">
		  <div class="row">

		    <div class="col-sm-2"></div>

			    <div class="col-sm-8">
			      	<h4><%= @chat_room.title %></h4>

					<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
					  <%= render @chat_room.messages %>
					</div>
					<br>

					<%= form_for @message, url: '#' do |f| %>
					  <div class="row">
						  	<div class="col-sm-11">
						    	<%= f.text_area :body, class: 'form-control bodyChat' %>
						    	<small class="text-muted">De 2 a 1000 caracteres</small>
							</div>
							<div class="col-sm-1">
								<%= button_tag( class: "chatButtonSend") do %>
								  <i class='fa fa-paper-plane btn btn-success' style="padding: 10px;"></i>
								<% end %>			
						    </div>
					  </div>
					<% end %>
			    </div>

		  		<div class="col-sm-2"></div>
			</div>
		</div>
    </div>
</div>

<div style="display:none">	
	<div class="card" id="dataMessage">
		  <div class="card-block">
		    <div class="row">
		      <div class="col-md-1">
		        <img alt="Edit Entry" src="/assets/user-chat-4453aab178a1c52f7a09ca1a811de1afd389c33a45f6d59fcd9b851e5402386c.png" width="40" height="40">
		      </div>
		      <div class="col-md-11">
		        <p class="card-text">
		          <span class="text-muted"></span><br>
		          hola
		        </p>
		      </div>
		    </div>
		  </div>
	</div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= form_with(model: @event, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :'Nombre Cita' %>
      <%= form.text_field :title, class: "form-control form-control-sm rounded-0" %>
    </div>

    <div class="form-group">
      <%= form.label :'Inicio' %><br>
      <%= form.datetime_select :start_time%>
    </div>

    <div class="form-group">
      <%= form.label :'Fin' %><br>
      <%= form.datetime_select :end_time %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar", class: "btn btn-success btn-sm float-right" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<% content_for :stylesheets do %>
  #topMenu {display: none}
  #footerHome {display: none}
<% end %>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="container">
  <!-- Tabla de citas -->
  <div class="row">

      <div class="col-md-5" >
          <img id="index_events" src="assets/background_index_event.png">
      </div>
      <div class="col-md-7" >
        <table class="table">
          <thead style="background-color: #3A3C42; color: white;">
            <tr>
              <th scope="col" class="text-center">Evento</th>
              <th scope="col" class="text-center">Inicio</th>
              <th scope="col" class="text-center">Fin</th>
               <th>
                  <a id="calendarModalEvent" href="#modalCalendar" class="text-white" data-toggle="modal">
                    <span class="fa fa-calendar"></span>
                  </a>
               </th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @events.each do |event| %>
              <tr>
                <td><%= event.title %></td>
                <td><%= event.start_time.strftime("%d-%m-%Y %H:%m") %></td>
                <td><%= event.end_time.strftime("%d-%m-%Y %H:%m") %></td>
                <td>
                  <a onclick="loadModalShowEvent('<%= event.id %>','#contentDetailEvent')" href="#contentModal" data-toggle="modal">Detalle</a>
                </td>
                <% if current_user.role_id != 3 %>
                  <td>
                    <a onclick="loadModalEditEvent('<%= event.id %>','#contentDetailEvent')" href="#contentModal" data-toggle="modal">Editar</a>
                  </td>
                  <td><%= link_to 'Eliminar', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-1" ></div>

  </div>
</div>



<!-- Modal Calendario-->
<div class="modal fade" id="modalCalendar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" style="width: 120% !important;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Calendario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
              <div class="col-md-12">
                <%= month_calendar events: @events do |date, events| %>
                  <%= date %>
                  <% events.each do |event| %>
                    <div class="text-danger font-weight-bold">
                      <%= event.title %>
                    </div>
                  <% end %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal Events-->
<div class="modal fade" id="contentModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width: 100% !important;">
      <div class="modal-header">
        <a href="/events" class="close"  aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </a>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
              <div class="col-md-12">
                <div id ="contentDetailEvent"></div>
              </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="/events" class="btn btn-secondary btn-sm">Cerrar</a>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<% content_for :stylesheets do %>
  #topMenu {display: none}
  #footerHome {display: none}
<% end %>
<div class="container">
	<p>
	  <strong>Cita:</strong>
	  <%= @event.title %>
	</p>

	<p>
	  <strong>Fecha inicio:</strong>
	  <%= @event.start_time %>
	</p>

	<p>
	  <strong>Fecha finalizacion:</strong>
	  <%= @event.end_time %>
	</p>
</div>

app/views/fundations/index.html.erb
<% for fundations in @fundation %>
<%= fundations.fundation_name %>
<% end %>

app/views/fundations/new.html.erb
<div class="container">
<%= form_for @fundation do |f| %>

	<div class="form-group">
        <%= f.label :'Nombre fundacion:' %><br />
        <%= f.text_field :fundation_name, class: "form-control form-control-sm rounded-0" %>
    </div>

    <div class="form-group">
        <%= f.label :'Direccion:' %><br />
        <%= f.text_field :address, class: "form-control form-control-sm rounded-0" %>
    </div>

	<div class="form-group">
        <%= f.label :'Telefono:' %><br />
        <%= f.text_field :phone, class: "form-control form-control-sm rounded-0" %>
    </div>

	<div class="form-group">
        <%= f.label :'Correo electronico:' %><br />
        <%= f.email_field :mail, class: "form-control form-control-sm rounded-0" %>
    </div>

    <div class="actions">
      <%= f.submit "Guardar", class: "btn btn-success btn-sm float-right" %>
    </div>

<% end %>
</div>

app/views/services/new.html.erb
<div class="container">
<%= form_for @service do |f| %>

	<div class="form-group">
        <%= f.label :'Servicio:' %><br />
        <%= f.text_field :service_name, class: "form-control form-control-sm rounded-0" %>
    </div>

    <div class="form-group">
        <%= f.label :'Descripcion:' %><br />
        <%= f.text_field :description, class: "form-control form-control-sm rounded-0" %>
    </div>

	<div class="form-group">
        <%= f.label :'Costo:' %><br />
        <%= f.text_field :cost, class: "form-control form-control-sm rounded-0" %>
    </div>

    <div class="actions">
      <%= f.submit "Guardar", class: "btn btn-success btn-sm float-right" %>
    </div>

<% end %>
</div>